import { SlashCommandBuilder, PermissionFlagsBits } from 'discord.js';
import { TRIGGER_ACTIONS, addCustomTrigger, getCustomTriggers, removeCustomTrigger } from '../../services/customTriggerService.js';
import { getGuildConfig, updateGuildConfig } from '../../services/config/guildConfig.js';
const SEND_MESSAGE_ACTION = 'send_message';
const SEND_MESSAGE_PREFIX = '__send_message__:';
const ACTION_LABELS = {
  [TRIGGER_ACTIONS.LOCK]:'Lock current channel',[TRIGGER_ACTIONS.UNLOCK]:'Unlock current channel',[TRIGGER_ACTIONS.HIDE]:'Hide current channel',[TRIGGER_ACTIONS.UNHIDE]:'Unhide current channel',
  [TRIGGER_ACTIONS.ADD_ROLE]:'Give a role',[TRIGGER_ACTIONS.REMOVE_ROLE]:'Remove a role',[TRIGGER_ACTIONS.DYNAMIC_ROLE]:'Give mentioned role',[TRIGGER_ACTIONS.REMOVE_DYNAMIC_ROLE]:'Remove mentioned role',[TRIGGER_ACTIONS.ADD_MEMBER]:'Add member to current channel',[TRIGGER_ACTIONS.CLEAR_MESSAGES]:'Clear messages',[TRIGGER_ACTIONS.BAN]:'Ban target',[TRIGGER_ACTIONS.KICK]:'Kick target',[TRIGGER_ACTIONS.WARN]:'Warn target',[TRIGGER_ACTIONS.MUTE]:'Mute target',[TRIGGER_ACTIONS.UNMUTE]:'Unmute target',[TRIGGER_ACTIONS.TIMEOUT]:'Timeout target (10m)',[TRIGGER_ACTIONS.UNTIMEOUT]:'Remove timeout',[TRIGGER_ACTIONS.JAIL]:'Jail member',[TRIGGER_ACTIONS.UNJAIL]:'Unjail member',[TRIGGER_ACTIONS.CHANGE_NICKNAME]:'Change nickname',[TRIGGER_ACTIONS.CHANGE_CHANNEL_NAME]:'Change channel name',
};
const actionLabel = item => item.action === SEND_MESSAGE_ACTION ? 'Send a message' : (ACTION_LABELS[item.action] || item.action);
export default { data:new SlashCommandBuilder().setName('trigger').setDescription('Create and manage word-based actions.').setDefaultMemberPermissions(PermissionFlagsBits.Administrator)
 .addSubcommand(s=>s.setName('add').setDescription('Create or update a word trigger.').addStringOption(o=>o.setName('word').setDescription('Exact trigger word or phrase.').setRequired(true).setMaxLength(100)).addStringOption(o=>o.setName('action').setDescription('What Orbit should do.').setRequired(true).addChoices(...Object.values(TRIGGER_ACTIONS).map(action=>({name:ACTION_LABELS[action],value:action})),{name:'Send a message',value:SEND_MESSAGE_ACTION})).addRoleOption(o=>o.setName('role').setDescription('Required role for this trigger.')).addStringOption(o=>o.setName('message').setDescription('Message to send.').setMaxLength(2000)))
 .addSubcommand(s=>s.setName('remove').setDescription('Remove a word trigger.').addStringOption(o=>o.setName('word').setDescription('Trigger to remove.').setRequired(true).setMaxLength(100)))
 .addSubcommand(s=>s.setName('list').setDescription('Show all configured word triggers.')), category:'core',
 async execute(interaction,config,client){try{const sub=interaction.options.getSubcommand();if(sub==='add'){const word=interaction.options.getString('word',true).trim(),action=interaction.options.getString('action',true),role=interaction.options.getRole('role'),messageText=interaction.options.getString('message');if(action===SEND_MESSAGE_ACTION){if(!messageText?.trim())return interaction.reply({content:'You must enter a message for this action.',ephemeral:true});const guildConfig=await getGuildConfig(client,interaction.guild.id),triggers=Array.isArray(guildConfig.customTriggers)?guildConfig.customTriggers:[],normalized=word.toLocaleLowerCase(),entry={trigger:normalized,action:SEND_MESSAGE_ACTION,roleId:`${SEND_MESSAGE_PREFIX}${Buffer.from(messageText.trim(),'utf8').toString('base64')}`},existing=triggers.findIndex(item=>String(item.trigger||'').trim().toLocaleLowerCase()===normalized);if(existing>=0)triggers[existing]=entry;else triggers.push(entry);await updateGuildConfig(client,interaction.guild.id,{customTriggers:triggers});return interaction.reply({content:`Trigger saved: **${entry.trigger}** → **Send a message**`,ephemeral:true});}if([TRIGGER_ACTIONS.ADD_ROLE,TRIGGER_ACTIONS.REMOVE_ROLE,TRIGGER_ACTIONS.JAIL,TRIGGER_ACTIONS.UNJAIL].includes(action)&&!role)return interaction.reply({content:'You must select a required role for this action.',ephemeral:true});if(role?.managed)return interaction.reply({content:'That role is managed and cannot be assigned.',ephemeral:true});const bot=interaction.guild.members.me;if(role&&bot&&role.position>=bot.roles.highest.position)return interaction.reply({content:'I cannot manage that role because it is above my highest role.',ephemeral:true});const entry=await addCustomTrigger(client,interaction.guild.id,word,action,role?.id||null);return interaction.reply({content:`Trigger saved: **${entry.trigger}** → **${actionLabel(entry)}**${entry.roleId?` → <@&${entry.roleId}>`:''}`,ephemeral:true});}if(sub==='remove'){const word=interaction.options.getString('word',true),removed=await removeCustomTrigger(client,interaction.guild.id,word);return interaction.reply({content:removed?`Removed trigger **${word.trim()}**.`:`No trigger was found for **${word.trim()}**.`,ephemeral:true});}const triggers=await getCustomTriggers(client,interaction.guild.id);if(!triggers.length)return interaction.reply({content:'No custom triggers are configured.',ephemeral:true});const lines=triggers.map(item=>`• **${item.trigger}** → ${actionLabel(item)}${item.action===SEND_MESSAGE_ACTION?'':item.roleId?` → <@&${item.roleId}>`:''}`);return interaction.reply({content:`**Custom Triggers (${triggers.length})**\n${lines.join('\n')}`.slice(0,2000),ephemeral:true});}catch(error){return interaction.reply({content:`Could not update triggers: ${error.message}`,ephemeral:true}).catch(()=>{});}},
};
